name: Tests
on:
  pull_request:
  push:
    branches: ['master']

jobs:
  test:
    name: Run tests ('${{ matrix.node_version }}')
    if: |
      !startsWith(github.event.pull_request.title, '[skip-ci]') &&
      !startsWith(github.event.pull_request.title, '[skip-package-ci]')
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node_version: [20, '${{ vars.NODE_VERSION }}' ]
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '${{ matrix.node_version }}'

    - name: Install Python setuptools
      run: python3 -m pip install setuptools

    - name: Install Dependencies
      run: npm install

    - name: Run tests
      run: npm run test
